### ISSUE TITLE
Create SPI for RasterSource

### ISSUE THREAD

**Issue by metasim** [geotrellis/geotrellis-contrib#10]
For the TODO list:

We'll eventually need to be able to do things like

```scala
val rs = RasterSource("https://s3-us-west-2.amazonaws.com/landsat-pds/c1/L8/149/039/LC08_L1TP_149039_20170411_20170415_01_T1/LC08_L1TP_149039_20170411_20170415_01_T1_B4.TIF")
```

or

```scala
val rs = RasterSource("s3://cbers-pds/CBERS4/AWFI/154/111/CBERS_4_AWFI_20160205_154_111_L4/CBERS_4_AWFI_20160205_154_111_L4_BAND15.tif")
```

or 
```scala
val rs = RasterSource("hdfs://my-dfs/my-magic-image.tif")
```

and have the library automatically determine how to resolve the scheme, in a similar manner as the current GT backend implementations.

**Comment by metasim** [comment]
It should also be able to resolve codec implementations based on file extension:

```scala
val rs = RasterSource("http://sentinel-s2-l1c.s3.amazonaws.com/tiles/32/T/NM/2017/1/4/0/B01.jp2")
```

**Comment by pomadchin** [comment]
Makes a lot of sense to create separate issues for such things, it's easy to forget everything.

**Comment by echeipesh** [comment]
Adding a note here from offline conversation. Since we have different read mechanism its actually ambiguous which way we're going to read a particular file type (ex: geotiff). This is all well and good but because there can be real and strong reasons to prefer one read mechanism vs the other at runtime it seems like being able to specify it using the `+` suffix on URI schema is a requirement.

Some examples:

        - http://example.com/file.tiff
            - Possible: GDAL, GeoTrellisGeoTiff
            - Result: First = GDAL
        - http+jvm://example.com/file.tiff
            - Return: GeoTrellisGeoTiff
        - http+gdal://example.com/file.tiff
            - Return: GDALRasterSource
        - /vsigzip//vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz
            - Return: GDAL
        - s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz
            - Note: same as above, consistent with RasterIO API
        - http+geotrellis-layer://example.com/catalog
            - Return: GeotrellisLayerRasterSource

This all looks like it can be directly supported by usual `canHandle(uri)` and `open(uri)` type of SPI interface.

**Comment by metasim** [comment]
I prefer having the the mechanism before the scheme to make it (marginally) easier to strip off.
[RasterFrames implementation of GDAL mode selection.](https://github.com/locationtech/rasterframes/blob/c1cce3d73d26d6df926534f445bb19510b91205b/core/src/main/scala/astraea/spark/rasterframes/ref/RasterSource.scala#L153)
