### ISSUE TITLE
RasterSource.reproject to CRS of underlying file should short-circuit

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-contrib#102]
Sometimes reprojection is done carelessly or reprojection of reprojected raster source could take it back to the starting CRS. In the cases we should certainly avoid returning `_ReprojectedRasterSource` and instead try to return either the base or the resampled version.

This is not a critical issue but important for performance and to minimize possible distortions of going through needless reprojection.

**Comment by echeipesh** [comment]
`GeoTrellisRasterSource` logic has been updated to do this in as of `3.11`

**Comment by pomadchin** [comment]
https://github.com/geotrellis/geotrellis-contrib/pull/202 also aligns with the idea of this PR to short-circuit the transformations; what needs to be done in particular (one of the possible solutions implementation strategy): 

1. make the [current reprojection method protected and rename it into smth internal](https://github.com/geotrellis/geotrellis-contrib/blob/aca902c5c9ff8e37169b6e8f95bc22decf7ae5e2/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala#L87)
2. implement a new one (with the name of the current) that will introduce the logic of the CRS checks

This will allow us to separate the pure reprojection logic from the CRS checks and will make the methods behavior more transparent. 

These changes are definitely required for the proper `GeoTiffRasterSources` work and for the `GDALRasterSources` as well (since in GDALRasterSources we're [stacking sequences of GDALWarpOptions transformations](https://github.com/geotrellis/geotrellis-contrib/blob/3d05e9c9ae45c68266b3c2f6a556a303102c0115/gdal/src/main/scala/geotrellis/contrib/vlm/gdal/Implicits.scala#L54) into a single GDALWarp object). 

The implementation of these changes can be a bit different from what I described i.e. without having a protected method just introduce an extra CRS check directly into the reproject function implementation, however it won't make the code more readable.
