### ISSUE TITLE
Expose API for retrieving nearest (unsampled) overview

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-contrib#196]
It should be possible to request the closest overview to a given `CellSize` from among a list of overviews (we do this in geotrellis here: https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala#L105).

The exact implementation in `RasterSource`s requires some thought but ideally there should be a way to read an extent from a list of overviews and retrieve an (unsampled) image which corresponds to said extent.

It might be worth noting that this won't fulfill the requirements by itself: the front end will need to be careful about which zoom levels it ends up requesting images from to avoid tiles of the wrong size (256x256 is the tile size for this strategy *only* at the zoom levels which are mirrored by overviews in the source tiff

**Comment by echeipesh** [comment]
Currently we expose the list of `resolutions`

https://github.com/geotrellis/geotrellis-contrib/blob/aca902c5c9ff8e37169b6e8f95bc22decf7ae5e2/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala#L73

Given that list you can ask to re-sample to one of your choice. I think we may need to implement some kind of snapping behavior where we returned one of the "direct-read" version of `RasterSource` rather than re-sampled version when possible. 

Given the above caveat it sounds like existing behavior may be sufficient for the issue. Are there things that would be helpful that are missing?

**Comment by pomadchin** [comment]
I think the issue is to double check that in cases we 100% match the overview resolution we're not doing [extra resampling step](https://github.com/geotrellis/geotrellis-contrib/blob/aca902c5c9ff8e37169b6e8f95bc22decf7ae5e2/vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffResampleRasterSource.scala#L107). It is a RF case.

I'm writing this comment here since I was on the initial meeting with Chris, and I agree that this issue description is not very clear.

**Comment by echeipesh** [comment]
I think the correct thing to do is to check here:
https://github.com/geotrellis/geotrellis-contrib/blob/aca902c5c9ff8e37169b6e8f95bc22decf7ae5e2/vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSource.scala#L47-L48

If we should be producing `GeoTiffResampleRasterSource` or `GeoTiffRasterSource`. Same goes for all calls to `resample` and `reproject`. Basically we should be short-circuiting to to the most direct implementation when possible.

**Comment by moradology** [comment]
This might be of interest still, but there's no special requirement to do this for RF and it looks as though this is no longer a priority
