### ISSUE TITLE
RasterSource Identification

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-contrib#197]
Currently `RasterSource` is expected to be identified by `uri`:

Previously `uri`:
https://github.com/geotrellis/geotrellis-contrib/blob/b954cbe21cd770ea0b36a2230f2c11074ec664ab/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala#L45

currently `dataPath`:
https://github.com/geotrellis/geotrellis-contrib/blob/aca902c5c9ff8e37169b6e8f95bc22decf7ae5e2/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala#L48

However there are at least two cases where that is not possible:
- `InMemoryRasterSource`: https://github.com/geotrellis/geotrellis-contrib/pull/138/files
- `MosaicRasterSource`: https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/MosaicRasterSource.scala

What we need a is a trait hierarchy to be mixed in with  implementations of `RasterSource` similar to what is discussed here: https://github.com/geotrellis/geotrellis-contrib/pull/138

This would allow the users of the interface to match against the mix-ins and pull out raster addresses if they're available.

**Comment by pomadchin** [comment]
Will drop a comment here, that GDAL has absolutely the same problem, since it can perform lazy VRT computations, and usually GDAL operates with named or unnamed datasets.

By name it usually understands the file location (when you read the initial dataset into memory), the VRT file location, in cases the operation creates a `.vrt` file as an output or _any string name (or empty)_ in case it is an in-memory thing only.

**Comment by pomadchin** [comment]
https://github.com/geotrellis/geotrellis-contrib/issues/182 can be used as an example of the places where both `path` and `name` can be useful to collect some extra information from the `RasterSource` to build the proper `Key` type.
