### ISSUE TITLE
Steamlined release process (like maml and GT Server) 

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/geotrellis-contrib#222]
The deployment best practices developed for:

- https://github.com/geotrellis/maml
and
- https://github.com/geotrellis/geotrellis-server/pull/138

have are something we'd like to see for this project as well. Copying the work done there might be sensible, but it would likely be time consuming given the context ops already has.

@echeipesh said @CloudNiner may have started a conversation about this?

But wanted to create this issue to track the conversation.

**Comment by CloudNiner** [comment]
@geotrellis/operations were you able or will you be able to schedule this within the next sprint? If not, I'd be happy to tackle this effort as we have a chunk of time open in this and the next sprint, assuming that we'd be following the template laid out in https://github.com/geotrellis/geotrellis-server/pull/138?

**Comment by hectcastro** [comment]
Sorry all, but this repository wasn't associated with our kanban board (it is now), so we never saw this issue.

If you want to take a first stab at it, that seems perfectly fine. As you mention, https://github.com/geotrellis/geotrellis-server/pull/138 is a good place to start because it is our most recent example of setting this up. https://github.com/geotrellis/maml/pull/98 is the attempt before that. Please feel free to assign us to review, or tag us on an early WIP PR if you hit any snags (I imagine that there may be some around artifact signing).

**Comment by CloudNiner** [comment]
Ah! Oops, no worries.

Alright, I'll take a swing at an initial pass at this. Looks like both the existing MAML/Server setups publish to Sonatype and Contrib publishes to bintray. Did you have any pre-existing expectations about migrating this project to sonatype so we're always publishing to the same place?

**Comment by CloudNiner** [comment]
@geotrellis/operations an immediate question -- looking through the other two setups, there's `GPG_KEY` and `GPG_PASSPHRASE`. Are those available in a CircleCI "Context" or some other place where if I just use them here in the gt-contrib circle ci config, they will be available? I don't have admin permissions on the geotrellis org to inspect the org settings on CircleCI.

**Comment by hectcastro** [comment]
> Did you have any pre-existing expectations about migrating this project to sonatype so we're always publishing to the same place?

Yeah, I think we're shooting to have anything we want to use across teams/projects in Sonatype.

> Are those available in a CircleCI "Context" or some other place where if I just use them here in the gt-contrib circle ci config, they will be available?

They can be, but they aren't for the `geotrellis-contrib` project configuration yet. We can add them to the project configuration tomorrow. I'd add it now, but I think that the key itself may be on physical media in the office.

**Comment by CloudNiner** [comment]
@geotrellis/operations the first potential snag. I [converted the tests to use a docker-compose setup](https://github.com/geotrellis/geotrellis-contrib/commit/c379d88e7ae51f160e860c05e60eea3ad0f42058) because we rely on a postgis test db and need the openjdk-gdal image for the gdal tests. 

It looks like I have three ways to approach this setup in CircleCI:
1. I can use docker-compose [via the `machine` executor](https://circleci.com/docs/2.0/docker-compose/#using-docker-compose-with-machine-executor) where supposedly the local docker-compose config will _just work_ 🤔: VM spinup time is higher in this mode and by default, there's no docker layer caching, but it can be enabled by a CircleCI Sales rep for an additional fee which I can't figure out from their pricing page. What is 200 credits per job run?
2. I can use docker-compose [via the `docker` executor](https://circleci.com/docs/2.0/docker-compose/#using-docker-compose-with-docker-executor): port forwarding and volumes are weird here because the host runs elsewhere. So there'd be some fiddling to get that right and ensure the sbt caching works correctly.
3. Skip docker-compose entirely in CI and just [run a db instance as a separate instance](https://circleci.com/docs/2.0/postgres-config/) on the `docker` executor, spinning it up in a step of the job: this option loses all reusability gained from the local docker-compose setup, but is clear, will likely have the fastest run times, and I can re-use the caching configuration from the MAML/Server CircleCI setups.

I'm inclined to attempt (1) to see how slow it is and if it truly is plug and play. If not, I think falling back to (3) is better than (2) because in either case we lose the pluggability of docker-compose and it's likely that the complexity and platform specific knowledge of (2) will be higher in the long run. Thoughts?

**Comment by hectcastro** [comment]
> They can be, but they aren't for the `geotrellis-contrib` project configuration yet. We can add them to the project configuration tomorrow. I'd add it now, but I think that the key itself may be on physical media in the office.

The following settings have been added to the `geotrellis-contrib` CircleCI project configuration:

- `GPG_KEY`
- `GPG_KEY_ID`
- `SONATYPE_PASSWORD`
- `SONATYPE_USERNAME`

> I converted the tests to use a docker-compose setup because we rely on a postgis test db and need the openjdk-gdal image for the gdal tests.

Just a note that we have centrally maintained `openjdk-gdal` container images on Quay now (used in production w/ RF): https://quay.io/repository/azavea/openjdk-gdal?tag=latest&tab=tags

> It looks like I have three ways to approach this setup in CircleCI:

Interesting. This is the first time we're encountering this scenario in CircleCI (needing another service available to execute tests). After reading through the docs, I agree with with an approach that rolls the dice on 1 and falls back to 3 if that doesn't work. 3 seems like the most hardened path within the context of CircleCI. Sucks that it requires breaking out of the comforts of Docker Compose though.

**Comment by CloudNiner** [comment]
> Just a note that we have centrally maintained openjdk-gdal container images on Quay now

🔥 I'll swap to that, looks like there's a JDK 8 + GDAL 2.4 image there so I'm good to go.

> The following settings have been added to the geotrellis-contrib CircleCI project configuration

Also awesome. I expect to get to that later today, will post back if there's any issues.

> After reading through the docs, I agree with with an approach that rolls the dice on 1

This totally worked without any modifications to the docker-compose. Which is great for now -- I love rolling double sixes. Looks like the caching setup copied from gt-server reduced run time from ~16.5 mins to ~9.5 mins on a re-run of a successful build: https://circleci.com/gh/geotrellis/workflows/geotrellis-contrib/tree/feature%2Fawf%2Fci -- you're looking for the first two green builds in that list to compare running https://github.com/geotrellis/geotrellis-contrib/commit/a027221c6678c81733344be1a034ceba5f3bfb39

I'm inclined to leave this setup in place for now, and if we run into CircleCI compute limits or they deprecate the `machine` executor or something, we re-evaluate at that time.

**Comment by hectcastro** [comment]
Wow. I really wasn't expecting it to work out. 🚤
