### ISSUE TITLE
LayoutTileSource.read and RasterSource.read return types do not match

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-contrib#37]
API questions/inconsistencies which aren't full-fledged work issues can live here

@echeipesh edit: Changing the issue to the one thing mentioned. We should make new issues for API consistency concerns rather than keeping a thread in github issues.

**Comment by moradology** [comment]
Different output types from these read functions. Seems less than ideal
https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala#L112
https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/LayoutTileSource.scala#L39

**Comment by echeipesh** [comment]
The file pointers have moved but I believe this issue refers to the fact that in

```scala
trait LayoutTileSource {
  def read(key: SpatialKey): Option[MultibandTile] =
}

trait RasterSource {
  def read(extent: Extent, bands: Seq[Int]): Option[Raster[MultibandTile]]
}
```

Where in the former we return the tile for the key while in the latter case we return the raster.
The original decision for the return types is as follows:

`RasterSource.read` will snap the `Extent` of the result to the available pixels, this information needs to be communicated to the user, who has no other access to it.

`LayoutTileSource` makes a promise that rasters returend will always match the extent and pixel count from the tile in `LayoutDefinition` specified by the `SpatialKey`. If the underlying source does not have enough pixels they will be buffered. In this case we do no return the Extent because:
1. It can readily calculated from `SpatialKey` which was given as input to `read` method if desired
2. `SpatialKey => Option[MultibandTile]` best matches the existing `ValueReader` interface which is approximated here.

**Comment by echeipesh** [comment]
Offline discussion didn't produce any strong feelings on this issue. Closing under "fine-for-now", to be re-opened if this discrepancy is going to start produce ugly client code or other concrete issues.
