### ISSUE TITLE
VSIPath does not understand .gz extensions

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-contrib#52]
Example of success using the `/vsigzip` and failure of translation from URI to vsi path

```scala
scala> import geotrellis.contrib.vlm.gdal._
import geotrellis.contrib.vlm.gdal._

scala> GDALRasterSource("/vsigzip//Users/eugene/N49W155.hgt.gz").extent
res7: geotrellis.vector.Extent = Extent(-155.0001388888889, 48.999861111111116, -153.99986111111113, 50.00013888888889)

scala> GDALRasterSource("file:/Users/eugene/N49W155.hgt.gz").extent
java.lang.Exception: Could not determine the paths for: file:/Users/eugene/N49W155.hgt.gz
  at geotrellis.contrib.vlm.gdal.VSIPath.<init>(VSIPath.scala:65)
  at geotrellis.contrib.vlm.gdal.GDAL$.open(GDAL.scala:55)
  at geotrellis.contrib.vlm.gdal.GDAL$$anonfun$3.apply(GDAL.scala:95)

scala> GDALRasterSource("file+gzip:/Users/eugene/N49W155.hgt.gz").extent
java.lang.Exception: Could not determine the paths for: file+gzip:/Users/eugene/N49W155.hgt.gz
  at geotrellis.contrib.vlm.gdal.VSIPath.<init>(VSIPath.scala:65)
  at geotrellis.contrib.vlm.gdal.GDAL$.open(GDAL.scala:55)
```

**Comment by jbouffard** [comment]
It looks like it failed because I didn't take the file URI format for macs into account; as this [pattern](https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/gdal/Patterns.scala#L35) won't match what you gave it. I think taking that into account when trying to [get the targetPath](https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/gdal/VSIPath.scala#L54-L57) should fix the issue.

**Comment by jbouffard** [comment]
Oh, I see. I'm surprised it doesn't work with that URI, though. If I have the time, I'll look into this more later this sprint.
